### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by artursmolarek** [drone-python/plugin-pypi#2]
Could you please provide example how to configure Drone with PyPI plugin? I was trying to use example from the official documentation, but with no success.
I'm getting `ERROR: Image not found` error. I'm using Drone **0.5**.

My config:

```
pipeline:
  build:
    image: python:2.7
    script:
    - python setup.py develop
  pypi:
    repository: https://pypi.myhost.com
    username: pypi
    password: pypi
```
